apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: integration-casperholders-cert
spec:
  secretName: integration-casperholders-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: integration.casperholders.io
  dnsNames:
    - integration.casperholders.io
